INSERT INTO companies (name, name_en, rss_url, site_url, sector, logo_url)
VALUES
    ('토스', 'Toss', 'https://toss.tech/rss.xml', 'https://toss.tech', 'domestic_fintech', 'https://www.google.com/s2/favicons?domain=toss.im&sz=64'),
    ('카카오페이', 'KakaoPay', 'https://tech.kakaopay.com/rss.xml', 'https://tech.kakaopay.com', 'domestic_fintech', 'https://www.google.com/s2/favicons?domain=kakaopay.com&sz=64'),
    ('네이버페이', 'NaverPay', 'https://medium.com/feed/naverfinancial', 'https://medium.com/naverfinancial', 'domestic_fintech', 'https://www.google.com/s2/favicons?domain=pay.naver.com&sz=64'),
    ('뱅크샐러드', 'Banksalad', 'https://blog.banksalad.com/rss.xml', 'https://blog.banksalad.com', 'domestic_fintech', 'https://www.google.com/s2/favicons?domain=banksalad.com&sz=64'),
    ('카카오뱅크', 'KakaoBank', 'https://tech.kakaobank.com/index.xml', 'https://tech.kakaobank.com', 'domestic_bank', 'https://www.google.com/s2/favicons?domain=kakaobank.com&sz=64'),
    ('케이뱅크', 'K Bank', 'https://medium.com/feed/kbanktech', 'https://www.kbanknow.com', 'domestic_bank', 'https://www.google.com/s2/favicons?domain=kbanknow.com&sz=64'),
    ('KB데이타시스템', 'KBDS', NULL, 'https://blog.kbds.co.kr', 'domestic_bank', 'https://www.google.com/s2/favicons?domain=kbds.co.kr&sz=64'),
    ('신한DS', 'Shinhan DS', NULL, 'https://www.shinhands.co.kr', 'domestic_bank', 'https://www.google.com/s2/favicons?domain=shinhands.co.kr&sz=64'),
    ('하나금융융합기술원', 'Hana Tech', NULL, 'https://hit.hanati.co.kr', 'domestic_bank', 'https://www.google.com/s2/favicons?domain=hit.hanati.co.kr&sz=64'),
    ('미래에셋증권', 'Mirae Asset', NULL, 'https://securities.miraeasset.com', 'domestic_securities', 'https://www.google.com/s2/favicons?domain=miraeasset.com&sz=64'),
    ('키움증권', 'Kiwoom', NULL, 'https://www.kiwoom.com', 'domestic_securities', 'https://www.google.com/s2/favicons?domain=kiwoom.com&sz=64'),
    ('한국투자증권', 'KIS', NULL, 'https://apiportal.koreainvestment.com', 'domestic_securities', 'https://www.google.com/s2/favicons?domain=koreainvestment.com&sz=64'),
    ('두나무', 'Dunamu', NULL, 'https://dunamu.com', 'domestic_securities', 'https://www.google.com/s2/favicons?domain=dunamu.com&sz=64'),
    ('업비트', 'Upbit', NULL, 'https://upbit.com', 'crypto', 'https://www.google.com/s2/favicons?domain=upbit.com&sz=64'),
    ('빗썸', 'Bithumb', NULL, 'https://www.bithumb.com', 'crypto', 'https://www.google.com/s2/favicons?domain=bithumb.com&sz=64'),
    ('코인원', 'Coinone', NULL, 'https://coinone.co.kr', 'crypto', 'https://www.google.com/s2/favicons?domain=coinone.co.kr&sz=64'),
    ('클레이튼', 'Klaytn', 'https://blog.kaia.io/feed/', 'https://blog.kaia.io', 'crypto', 'https://www.google.com/s2/favicons?domain=kaia.io&sz=64'),
    ('Stripe', 'Stripe', 'https://stripe.com/blog/feed.rss', 'https://stripe.com/blog/engineering', 'global_fintech', 'https://www.google.com/s2/favicons?domain=stripe.com&sz=64'),
    ('Plaid', 'Plaid', 'https://plaid.com/blog/rss.xml', 'https://plaid.com/blog', 'global_fintech', 'https://www.google.com/s2/favicons?domain=plaid.com&sz=64'),
    ('Robinhood', 'Robinhood', NULL, 'https://robinhood.engineering', 'global_fintech', 'https://www.google.com/s2/favicons?domain=robinhood.com&sz=64'),
    ('Monzo', 'Monzo', NULL, 'https://monzo.com/blog/technology', 'global_fintech', 'https://www.google.com/s2/favicons?domain=monzo.com&sz=64'),
    ('Revolut', 'Revolut', 'https://medium.com/feed/revolut', 'https://medium.com/revolut', 'global_fintech', 'https://www.google.com/s2/favicons?domain=revolut.com&sz=64'),
    ('Wise', 'Wise', 'https://medium.com/feed/wise-engineering', 'https://medium.com/wise-engineering', 'global_fintech', 'https://www.google.com/s2/favicons?domain=wise.com&sz=64'),
    ('Coinbase', 'Coinbase', NULL, 'https://www.coinbase.com/blog/landing/engineering', 'crypto', 'https://www.google.com/s2/favicons?domain=coinbase.com&sz=64'),
    ('Binance', 'Binance', NULL, 'https://www.binance.com/en/blog/tech', 'crypto', 'https://www.google.com/s2/favicons?domain=binance.com&sz=64')
ON CONFLICT DO NOTHING;
